Repository woowacourse-elegant-object/elegant-object-study, pull requests merged in 2021-04, with the labels that each got.

#6 docs: 수리 1.3, 2.1 업로드
  1장-출생/3절-생성자에_코드를_넣지_마세요/suri.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/suri.md
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/suri.md
  2장-학습/3절-항상-인터페이스를-사용하세요/suri.md
Labels: 1.3, 2.1

#13 suri 2.2_2.3 제출합니다.
  1장-출생/3절-생성자에_코드를_넣지_마세요/suri.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/suri.md
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/suri.md
  2장-학습/3절-항상-인터페이스를-사용하세요/suri.md
Labels: 2.2, 2.3

#9 feat: 1.3, 2.1 검프 정리글 업로드
  1장-출생/1절-er로_끝나는_이름을_사용하지_마세요/gump.md
  1장-출생/2절-생성자_하나를_주_생성자로_만드세요/gump.md
  1장-출생/3절-생성자에_코드를_넣지_마세요/gump.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/gump.md
Labels: 1.3, 2.1

#10 docs: 1-3, 2-1 조앤 정리글 작성
  1장-출생/3절-생성자에_코드를_넣지_마세요/joanne.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/joanne.md
Labels: 1.3, 2.1

#11 1-3, 2-1 : 코다 정리글
  1장-출생/3절-생성자에_코드를_넣지_마세요/koda.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/koda.md
Labels: 1.3, 2.1

#16 docs: 2.2, 2.3 웨지 정리글 제출
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/wedge.md
  2장-학습/3절-항상-인터페이스를-사용하세요/wedge.md
Labels: 2.2, 2.3

#18 2.2 : 최소한 뭔가는 캡슐화하세요
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/nabom.md
Labels: 2.2, 최소한 뭔가는 캡슐화하세요

#25 docs: 2.2 2.3 파즈 정리글 업로드
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/bepoz.md
  2장-학습/3절-항상-인터페이스를-사용하세요/bepoz.md
Labels: 2.2, 2.3, 최소한 뭔가는 캡슐화하세요, 항상 인터페이스를 사용하세요

#57 docs: 2.6, 2.7 코다 정리글 업로드
  .DS_Store
  2장-학습/.DS_Store
  2장-학습/6절-불변-객체로-만드세요/koda.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/koda.md
Labels: 2.6, 2.7

#12 docs: 2.2, 2.3 씨유 정리글
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/cu.md
  2장-학습/3절-항상-인터페이스를-사용하세요/cu.md
Labels: 2.2, 2.3

#17 2.3 항상 인터페이스를 사용하세요
  2장-학습/3절-항상-인터페이스를-사용하세요/nabom.md
Labels: 2.3, 항상 인터페이스를 사용하세요

#19 2.2, 2.3 코다 정리글 업로드
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/koda.md
  2장-학습/3절-항상-인터페이스를-사용하세요/koda.md
Labels: 2.2, 2.3

#20 docs: 2.2 2.3 검프 정리글 업로드
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/gump.md
  2장-학습/3절-항상-인터페이스를-사용하세요/gump.md
Labels: 2.2, 2.3, 최소한 뭔가는 캡슐화하세요, 항상 인터페이스를 사용하세요

#21 docs: 2.2 2.3 조앤 정리글 작성
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/joanne.md
  2장-학습/3절-항상-인터페이스를-사용하세요/joanne.md
Labels: 2.2, 2.3, 최소한 뭔가는 캡슐화하세요, 항상 인터페이스를 사용하세요

#23 docs: 1.3 2.1 완태 정리글 작성
  1장-출생/3절-생성자에_코드를_넣지_마세요/wannte.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/wannte.md
Labels: 1.3, 2.1

#26 docs: 1.3 2.1 다니 정리글 업로드
  1장-출생/3절-생성자에_코드를_넣지_마세요/danyee.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/danyee.md
Labels: 1.3, 2.1, 가능하면 적게 캡슐화하세요, 생성자에 코드를 넣지 마세요

#28 2.4 2.5 나봄 정리
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/nabom.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/nabom.md
Labels: 2.4, 2.5, 메서드 이름을 신중하게 선택하세요, 퍼블릭 상수를 사용하지 마세요

#29 docs : 웨지 2-4,2-5 독후감 작성
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/wedge.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/wedge.md
Labels: 2.4, 2.5, 메서드 이름을 신중하게 선택하세요, 퍼블릭 상수를 사용하지 마세요

#30 docs: 2.4 2.5 조앤 정리글 작성
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/joanne.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/joanne.md
Labels: 2.4, 2.5, 메서드 이름을 신중하게 선택하세요, 퍼블릭 상수를 사용하지 마세요

#31 docs: 2.2, 2.3 완태 정리글
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/wannte.md
  2장-학습/3절-항상-인터페이스를-사용하세요/wannte.md
Labels: 2.2, 2.3

#32 docs: suri 2.4 2.5 정리글
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/suri.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/suri.md
Labels: 2.4, 2.5, 메서드 이름을 신중하게 선택하세요, 퍼블릭 상수를 사용하지 마세요

#33 docs: 씨유 2.4, 2.5 정리글 업로드
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/cu.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/cu.md
Labels: 2.4, 2.5

#34 docs: 2.5, 2.5 코다 정리글 업로드
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/koda.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/koda.md
Labels: 2.4, 2.5

#35 feat: 1.3, 2.1 손너잘 추가
  1장-출생/3절-생성자에_코드를_넣지_마세요/neozal.md
  2장-학습/1절-가능하면_적게_캡슐화하세요/neozal.md
Labels: 1.3, 2.1, 생성자에 코드를 넣지 마세요, 최소한 뭔가는 캡슐화하세요

#36 feat: 2.2 2.3 손너잘 추가
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/neozal.md
  2장-학습/3절-항상-인터페이스를-사용하세요/neozal.md
Labels: 2.2, 2.3

#37 feat: 2.4 2.5 손너잘 추가
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/neozal.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/neozal.md
Labels: 2.4, 2.5

#38 feat: 2.4, 2.5 검프 정리글 업로드
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/gump.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/gump.md
Labels: 2.4, 2.5

#39 docs: 2.4 2.5 파즈 정리글 업로드
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/bepoz.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/bepoz.md
Labels: 2.4, 2.5, 메서드 이름을 신중하게 선택하세요, 퍼블릭 상수를 사용하지 마세요

#43 나봄 : 2.6 2.7 정리
  2장-학습/6절-불변-객체로-만드세요/nabom.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/nabom.md
Labels: 2.6, 2.7

#44 docks: 씨유 2.6, 2.7 정리글 업로드
  2장-학습/6절-불변-객체로-만드세요/cu.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/cu.md
Labels: 2.6, 2.7

#45 docs : 웨지 2-6,2-7 정리 작성
  2장-학습/6절-불변-객체로-만드세요/wedge.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/wedge.md
Labels: 2.6, 2.7

#46 feat: 2.6 2.7 손너잘 추가
  2장-학습/6절-불변-객체로-만드세요/neozal.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/neozal.md
Labels: 2.6, 2.7

#47 docs: 2.2 2.3 다니 정리글 업로드
  2장-학습/2절-최소한_뭔가는_캡슐화하세요/danyee.md
  2장-학습/3절-항상-인터페이스를-사용하세요/danyee.md
Labels: 2.2, 2.3, 최소한 뭔가는 캡슐화하세요, 항상 인터페이스를 사용하세요

#48 docs: 2.6 2.7 파즈 정리글 업로드
  2장-학습/6절-불변-객체로-만드세요/bepoz.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/bepoz.md
Labels: 2.6, 2.7, 문서를 작성하는 대신 테스트를 만드세요, 불변 객체로 만드세요

#49 docs: 수리 2.6, 2.7 업로드
  2장-학습/6절-불변-객체로-만드세요/suri.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/suri.md
Labels: 2.6, 2.7, 문서를 작성하는 대신 테스트를 만드세요, 불변 객체로 만드세요

#51 docs: 2.8 2.9 파즈 정리글 업로드
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/bepoz.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/bepoz.md
Labels: 2.8, 2.9, 모의 객체(Mock) 대신 페이크 객체(Fake)를 사용하세요, 인터페이스를 짧게 유지하고 스마트(smart)를 사용하세요

#52 docs: 2.4 2.5 다니 정리글 업로드
  2장-학습/4절-메서드-이름을-신중하게-선택하세요/danyee.md
  2장-학습/5절-퍼블릭-상수를-사용하지-마세요/danyee.md
Labels: 2.4, 2.5, 메서드 이름을 신중하게 선택하세요, 퍼블릭 상수를 사용하지 마세요

#54 docs: 2.6, 2.7 조앤 정리글 업로드
  2장-학습/6절-불변-객체로-만드세요/joanne.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/joanne.md
Labels: 2.6, 2.7, 문서를 작성하는 대신 테스트를 만드세요, 불변 객체로 만드세요

#55 docs: 2.8, 2.9 조앤 정리글 업로드
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/joanne.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/joanne.md
Labels: 2.8, 2.9, 모의 객체(Mock) 대신 페이크 객체(Fake)를 사용하세요, 인터페이스를 짧게 유지하고 스마트(smart)를 사용하세요

#56 docs: 2.6 2.7 다니 정리글 업로드
  2장-학습/6절-불변-객체로-만드세요/danyee.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/danyee.md
Labels: 2.6, 2.7, 문서를 작성하는 대신 테스트를 만드세요, 불변 객체로 만드세요

#60 docs: 2.6, 2.7 포모 정리글 업로드
  2장-학습/6절-불변-객체로-만드세요/pomo.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/pomo.md
Labels: 2.6, 2.7

#61 docs : 2-8, 2-9 정리 작성
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/wedge.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/wedge.md
Labels: 2.8, 2.9, 모의 객체(Mock) 대신 페이크 객체(Fake)를 사용하세요, 인터페이스를 짧게 유지하고 스마트(smart)를 사용하세요

#62 docs: 2.8 2.9 포모 정리글 업로드
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/pomo.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/pomo.md
Labels: 2.8, 2.9

#63 docs: 2.6 2.7 검프 정리글 업로드
  2장-학습/6절-불변-객체로-만드세요/gump.md
  2장-학습/7절-문서를-작성하는-대신-테스트를-만드세요/gump.md
Labels: 2.6, 2.7

#64 docs: 2.8, 2.9 검프 정리글 업로드
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/gump.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/gump.md
Labels: 2.8, 2.9

#66 nabom: 2.8. 2.9 정리
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/nabom.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/nabom.md
Labels: 2.8, 2.9

#70 조이 1.1~1.2 업로드
  1장-출생/1절-er로_끝나는_이름을_사용하지_마세요/joy.md
  1장-출생/2절-생성자_하나를_주_생성자로_만드세요/joy.md
Labels: 1.1, 1.2

#84 docs: 2.8 2.9 다니 정리글 업로드
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/danyee.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/danyee.md
Labels: 2.8, 2.9, 모의 객체(Mock) 대신 페이크 객체(Fake)를 사용하세요, 인터페이스를 짧게 유지하고 스마트(smart)를 사용하세요

#67 suri: 2.8 2.9 정리
  2장-학습/8절-모의-객체(Mock)-대신-페이크 객체(Fake)를-사용하세요/suri_2.8.md
  2장-학습/9절-인터페이스를-짧게-유지하고-스마트(smart)를-사용하세요/suri_2.9.md
Labels: 2.8, 2.9
